---
- name: Download App Details from Tetration to a YAML file
  hosts: mycompany
  gather_facts: no

  tasks:
  - name: Get creds from vault
    include_vars: ./creds.yml
    no_log: true

  - name: Download all App details from the cluster to a YAML file
    tetration_apps_to_yaml:
      hostname: '{{ inventory_hostname }}'
      api_key: '{{ API_KEY }}'
      api_secret: '{{ API_SECRET }}'
      dest: 'mycompany_apps.yml'
      validate_certs: False
    delegate_to: localhost