---
- name: Upload Scopes to Tetration from a YAML file
  hosts: mycompany_pov
  gather_facts: no

  tasks:
  - name: Get creds from vault
    include_vars: ./creds.yml
    no_log: true

  - name: Upload Scopes to the cluster from the YAML file
    tetration_add_scope_from_yaml:
      hostname: '{{ inventory_hostname }}'
      api_key: '{{ API_KEY }}'
      api_secret: '{{ API_SECRET }}'
      source: 'test_scopes.yml'
      validate_certs: False
    delegate_to: localhost
